export PS1="${debian_chroot:+($debian_chroot)}\e[0;32m\u@remote_42\e[m -> \e[1;33m\W\e[m\$ "
export PS1="${debian_chroot:+($debian_chroot)}\e[30;1m\u@remote_42\e[36;1m\]\W \[\e[32;1m\]→ \[\e[0m\]"
export PS1="\[\e[0;37m\]\[\e[30;1m\]\u@\h \[\e[36;1m\]\W \[\e[32;1m\]→ \[\e[0m\]"
export PS1="\e[0;32m\u@remote_42 \e[36;1m\W \e[32;1m→ \e[0m"
